version: "3.7"

services:
  good-morning:
    container_name: good-morning
    image: hibare/good-morning
    hostname: good-morning
    env_file:
      - ./.env
    dns:
      - 1.1.1.3
      - 8.8.8.8
    restart: unless-stopped
